### ISSUE TITLE
Does not save the information on the product after removing icons

### ISSUE THREAD

**Issue by ghost** [CharlieEtienne/wash-care-symbols-for-woocommerce#1]
Hi,

I have detected a small error in your plugin. In a product with icons added, when trying to remove them, the information in the product is not saved.I mean that the removed icons reappear.

Tks!

**Comment by CharlieEtienne** [comment]
Hi @Lendarius, unfortunately, I don't reproduce. 

Could you give more details about your installation, WP version, WooCommerce version, installed plugins ?

Thanks,

Charlie

**Comment by Lendarius** [comment]
Hi @CharlieEtienne,

You can test it here
wordpress.lendarius.com/wp-admin/
CharlieEtienne
keEg82!CY7

i have only woocommerce and your plugin active.

Tks.

I will edit/delete the comment after you access.

**Comment by ghost** [comment]
Hi @CharlieEtienne 

Any news about this issue?

**Comment by CharlieEtienne** [comment]
Hi @Lendarius, I did some tests and I finally understood what bug we've got here. We can remove one item if we have more than one in a field, but we can't remove it if the field has only one item. That means the field cannot be empty. I'll see what I can do to fix that.

I deleted your post with the credentials to keep your test site safe.

Cheers,

Charlie

**Comment by ghost** [comment]
Hi @CharlieEtienne!

That's exactly it! Let me know when you have a new version and I can help you test it.

Thank you and keep up with the good work!

**Comment by CharlieEtienne** [comment]
You can update to v2.1.8, it should be fixed. Thanks!
