### ISSUE TITLE
Parse error when activating the plugin

### ISSUE THREAD

**Issue by fernandotellado** [CharlieEtienne/wash-care-symbols-for-woocommerce#2]
Hi!

Thank You for the great idea and plugin 🙂

I’ve tried to activate in a tests site and it doesn’t and showed this error:

`Parse error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /…/…/wp-content/plugins/wash-care-symbols-for-woocommerce/wash-care-symbols-for-woocommerce.php on line 23
`
I’ve tested the plugin against a lot of PHP versions and … 

– Don’t work with PHP 7.1.x (minimal version is 7.2.x)
– Don’t work with PHP 7.2.x
– Don’t work with PHP 7.3.x
– Don’t work with PHP 7.4.x

Works fine with PHP 8.0.3! 😮

**Comment by CharlieEtienne** [comment]
Hi @fernandotellado and thanks for this issue.
You're right, the minimal version of 7.2 is wrong. However, it should work with >= 7.4...
I'm running php 7.4.7 on my local environnment and it works fine.

Anyway I'll remove the variable type so the minimal required version becomes 7.2 back again.

Thanks,

**Comment by CharlieEtienne** [comment]
You should be able to update to version 2.1.9 now !

**Comment by fernandotellado** [comment]
Yep :)

tested with PHP vos 7.3.27, 7.4.16 and 8.0.3 y works fine :)
