### ISSUE TITLE
Order of output into Additional info tab, Order of symbols in output, some new symbols

### ISSUE THREAD

**Issue by pyotr** [CharlieEtienne/wash-care-symbols-for-woocommerce#3]
Hello 
1. i changed order of the output inside Additional info tab from before attributes to after attributes.
2. Also i change order of symbols - cause my order seems to me more spread into clothing industry.
3. Also i need new symbols for dry cleaning - for example P inside circle with line at the bottom - it means delicate mode of dry cleaning - do you have this symbols? - sure i can create it myself also 
4. i am new to GitHub - so i can't create pull request 
5. i can fork your project if needed
6. i can't include my php file here (

**Comment by CharlieEtienne** [comment]
If you really don't manage to open a PR you could always send me your php file in an email BUT this is not this complicated:

1. Create a personal fork of the project on Github.
2. Clone the fork on your local machine. Your remote repo on Github is called `origin`. (Open a terminal, browse to your working folder with `cd myfolder`, and run `git clone https://github.com/pyotr/wash-care-symbols-for-woocommerce`)
3. Create a new branch to work on from master by running `git branch <new-branch>`
4. Implement/fix your feature.
5. Follow the code style of the project, including indentation.
6. Commit your code to your work branch by running `git add .` then `git commit -m "your commit message"`
7. Push your branch to your fork on Github, the remote origin with the command `git push`
8. From your fork open a pull request in the master branch. (Browse to [original repo PR page](https://github.com/CharlieEtienne/wash-care-symbols-for-woocommerce/pulls) and click on New pull request button)

Your help is appreciated, so I could help you to make it work

> Also i need new symbols for dry cleaning - for example P inside circle with line at the bottom - it means delicate mode of dry cleaning - do you have this symbols? - sure i can create it myself also

I added all symbols I found, so I don't have this one. 

Cheers,

Charlie

**Comment by CharlieEtienne** [comment]
I just added 10 new symbols for professional cleaning in [2.3.0](https://github.com/CharlieEtienne/wash-care-symbols-for-woocommerce/releases/tag/2.3.0).

I close this for inactivity but I will reopen it if needed.
